//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace EFExampleProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        [Required(ErrorMessage ="Username cannot be empty")]
        [MinLength(3,ErrorMessage ="Username should be of min 3 chars")]
        public string username { get; set; }
        [Required(ErrorMessage = "Password cannot be empty")]
        [RegularExpression("[0-9][0-9][0-9][0-9]",ErrorMessage ="Invalid password format")]
        public string password { get; set; }
    }
}
